---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hannahm-test-redis-pvc-data
  labels:
    username: hannahm
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi










